### ISSUE TITLE
Create a getServiceRegistrationByAddress()

### ISSUE THREAD

**Issue by arturgontijo** [singnet/platform-contracts#36]
It would be useful to have a function that returns service's info using only an agent address as input.
One of its use is to `rename` a service already published.

```
function getServiceRegistrationByAddress(address agentAddress) external view
            returns (bool found, bytes32 orgName, bytes32 name, bytes32 servicePath, bytes32[] serviceTags);
```

**Comment by astroseger** [comment]
Agent was depricated, so I close it.
