### ISSUE TITLE
add more events to MultiPartyEscrow contract

### ISSUE THREAD

**Issue by astroseger** [singnet/platform-contracts#44]
Events are cheap, so we can use more of them. But we probably shouldn't add events to each function either. So let's define list of events here. We need feedback from  the "server" (daemon) and the "client" (dapp).

**Comment by tiero** [comment]
I imagine at least:

* ChannelOpen
* ChannelReopen
* ChannelSuspended
* ChannelClaimed

(whatever names you want)

**Comment by astroseger** [comment]
I think we should think a little bit why we need them. And events also contains information, not only names :)

**Comment by tiero** [comment]
Yup, it depends on the client off-chain implementation and what can be useful for them. I omitted parameters cause I don't know yet

**Comment by astroseger** [comment]
Cool.. It is why I've created this issue, because we don't have this information now, and we should wait until we have feed back from "daemon"-team and "client"-team....

**Comment by astroseger** [comment]
was done in #69 . Should we close it?
