### ISSUE TITLE
using SafeMath in MultiPartyEscrow contract

### ISSUE THREAD

**Issue by astroseger** [singnet/platform-contracts#45]
In the current version of MultiPartyEscrow contract I'm not using SafeMath, but I'm not completely sure that it is right (It is why I left the comment about SafeMath in the code). 

My arguments for not using SafeMath are following:
1. I already check for overflow attack inside the code directly or indirectly via balance of AGI tokens (to perform attack you will need to have  ~2^256 AGI tokens). All operations are done only after I check their "validity" (that you really have given amount of tokens).
2. If overflow attack is still possible it means that there is a bug in the code. If SafeMath catch it, it is already too late, because logic of MPE is already broken somewhere.  
3. All possible overflow attacks must be tested via unit tests anyway.   
4. So it seems that SafeMath is overkill here. For normal computer language I would still use it, but here we pay gas for it, so I'm hesitating....

**Comment by tiero** [comment]
Can you test with real numbers the point 4 to understand how much gas it cost more?

Consider that it can be deployed as a library and shared within multiple contracts, and this it's less expensive at the deploy time.

**Comment by astroseger** [comment]
We've added SafeMath in https://github.com/singnet/platform-contracts/pull/49
However we spend more gas now:

Difference in Gas prices (without SafeMath/ with SafeMath):
channelClaim 65520 / 66116 (+596 gas)
channelClaimTimeout 29272 / 29485 (+213 gas)
channelExtendAndAddFunds 39246 / 39538 (+292 gas)
deposit 49146 / 49295 (+149 gas)
openChannel 139420/139657 (+237 gas)
