### ISSUE TITLE
do we need openChannelByRecipient logic in MultiPartyEscrow contract

### ISSUE THREAD

**Issue by astroseger** [singnet/platform-contracts#47]
We have to decide do we need open payment channel from the server side. This logic was implement (link to the implementable can be found bellow ), but we remove it from the current version, because we might not need it. 

The implementation can be found here:
https://github.com/singnet/platform-contracts/pull/39/commits/52ca590e61aa0fb16e3f692205ae581726936a03
More precise here:
https://github.com/singnet/platform-contracts/blob/52ca590e61aa0fb16e3f692205ae581726936a03/contracts/MultiPartyEscrow.sol#L101-L130
https://github.com/singnet/platform-contracts/blob/52ca590e61aa0fb16e3f692205ae581726936a03/contracts/MultiPartyEscrow.sol#L30
(and corresponding unit tests are also in this commit)

There are several facts that should be considered
1. openChannel is relatively cheap (it cost only about ~120.000 - 150.000 gas)
2. The channel for the given service+region should be opened only once. This channel will exists forever and can be reused unlimited number of times. 
3. openChannelByRecipient is ~50.000 gas more expensive then openChannel (because we need to check the signature and store the message in order to prevent replay attack)

Keeping in mind these facts, let's consider possible scenario of using openChannelByRecipient. 
1. "Secure scenario". Server can open the channel by openChannelByRecipient and wait the confirmation from the blockchain. It is obvious that this scenario is fully equivalent to the scenario in which the client open the channel, except now it is the server who pays for gas.  But openChannelByRecipient is more expensive! So for the server it would be better to ask the client to open the channel, and after give the client discount (it could be done transparent for everybody via SDK+daemon). 
2. "Insecure scenario".  The server openChannelByRecipient but doesn't wait the confirmation from the blockchain and starts to work with the client right away. We can actually imagine the similar scenario using openChannel: the client sends openChannel request to the blockchain and ask the server to start to work right away. Server could check blockchain transaction that have been sent by the client in order to be sure that the client indeed sent the transaction. Of course, in any case, the client can perform overspending attack. But it seems that "openChannelByRecipient" is more "secure" for the server here. 

Conclusion:
- If we follow "secure" scenario, then we shouldn't use openChannelByRecipient. If server would like to pay for gas he can make discount to the client (it can be made automatically via SDK+daemon).
- The only one situation where using of openChannelByRecipient might be justified is the "insecure scenario" where we don't want to wait the confirmation from the blockchain after opening the channel. But even here there are alternatives (we still can use openChannel). 

So the main question is:
- Do we really need this "insecure" scenario where we open the channel and don't wait the confirmation?

**Comment by pennachin** [comment]
Having the server open the channel was meant to make clients' (user, developer, integrator all being "clients" here) lives easier.  

In the secure scenario:
- End user's life is "easier" but more confusing, as they have to wait for a tx they didn't start or knew about to be confirmed. 
- Developers and integrators probably don't care either way. They have long-lived relationships with service providers, so the initial confirmation latency is irrelevant. Latency for adding funds as they're spent would matter but we can safely design logic for that.

In the insecure scenario:
- End user's life is indeed easier.
- Developers and integrators don't have rely on our logic to ensure channels aren't depleted leading to a service interruption.

So I agree we don't need `openChannelByRecipient` unless we need the insecure scenario. I am tempted to mark this as "post-beta", as it seems it really only matters once we have a SDK and beta dApp.

**Comment by ksridharbabuus** [comment]
Now we have openChannelByThirdParty in the latest version of MPE.
