### ISSUE TITLE
Combine metadata on registry contracts

### ISSUE THREAD

**Issue by raamb** [singnet/platform-contracts#65]
As part of MPE support the registry structure was changed and a new metadata construct was added as an off chain component described [here](https://github.com/singnet/wiki/blob/master/multiPartyEscrowContract/MPEServiceMetadata.md) 
The original registry however already has an on chain field called metadata. We want to combine these two and have a single metadata field which captures all the relevant data points.

**Comment by raamb** [comment]
Also 

- Remove path, add DisplayName to metadata
- Rename metadata hash to metadata uri in the contract.

**Comment by astroseger** [comment]
was done by #70
