### ISSUE TITLE
Store service encoding in the Registry. 

### ISSUE THREAD

**Issue by raamb** [singnet/platform-contracts#68]
Store the Daemon service encoding in the Registry

**Comment by astroseger** [comment]
will be done by https://github.com/singnet/snet-cli/pull/103

**Comment by vsbogd** [comment]
See https://github.com/singnet/snet-cli/pull/103#issuecomment-437307016 and issue https://github.com/singnet/snet-daemon/issues/103 there are two more values which can be moved into registry:
- service_type
- payment_expiration_threshold

**Comment by astroseger** [comment]
was done by singnet/snet-cli#103
