### ISSUE TITLE
Should we remove require(msg.sender == channels[channelId].sender) from channelClaimTimeout?

### ISSUE THREAD

**Issue by astroseger** [singnet/platform-contracts#74]
I propose to discuss removing require(msg.sender == channels[channelId].sender) in channelClaimTimeout. 
There is no security issues in this, because money are send back to the channels[channelId].sender.

Pros:
- A third party (for example SingularityNet), could monitor channels and "close" forgotten by both parties channels. There is no any advantages for a third party though.

Cons:
-  we could have a situation in which a third party initiate channelClaimTimeout and the sender initiate channelExtendAndAddFunds. There is a race condition (in the sense that result depends on the order who first), but there is not the problem. If channelExtendAndAddFunds is first then channelClaimTimeout fails. If channelClaimTimeout is first then channelExtendAndAddFunds is accepted, but final amount in the channel will be less (because some funds will by send back by channelClaimTimeout). 

We should think more about it...

**Comment by ksridharbabuus** [comment]
@astroseger my suggestion is leave it to the user to make the system completely decentralized and we will no need to manage separate list of address who can execute this function.

**Comment by astroseger** [comment]
@ksridharbabuus  but why need the list of address who can execute this function? My proposition was that everybody could execute channelClaimTimeout.

**Comment by ksridharbabuus** [comment]
What my thought process is it should be done  by the sender or by the
foundation even though there is no impact.

**Comment by ksridharbabuus** [comment]
@astroseger Shall we conclude this issue so that we can implement for Beta itself. Thanks!

**Comment by astroseger** [comment]
This great idea has not found understanding among our community. They are cruel and want users to close claim timeout by themselves :)

**Comment by ksridharbabuus** [comment]
Mostly many of them will be thinking to leave the control over to the user, that's what even I observed many decentralized platforms and it make sense as well. Thanks.
