### ISSUE TITLE
uniqueness of organizationName problem (google problem)

### ISSUE THREAD

**Issue by astroseger** [singnet/platform-contracts#76]
Anyone can register organization with the name "google". It means that: then real google come and try to register they will be very upset. Not to mention the problem of phishing.

The solution is following:
- We should remove organizationName and replace it with globalOrgIndex. So the searching key will be not organizationName but globalOrgIndex
- We make a field organizationDisplayName (which should be not bytes32 but string to allow any organization names )
- All these will be masked out from the dApp user, but of course we will need to select right google from many googles :)

- We should also remove serviceName from service registration. We already have serviceDisplayName in metadata. So the service name to be shown to the user will be serviceDisplayName from metadata!
- Instead we will have globalServiceIndex (continues numbering of services in the whole singularity net)

As result we will have unique ID for each service. Of course it will require some work from dApp, but, at the moment, it is the only one solution which I could find. And I think it is a good solution.

**Comment by raamb** [comment]
@astroseger This is a common problem for companies like Twitter, Instagram etc. They handle it via the verified badge as described [here](https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts). I believe that we decided to go the verification route when this came up in our HK visit but not sure though. 
cc @ksridharbabuus @vforvalerio87  @vsbogd

**Comment by astroseger** [comment]
@raamb  I was talking about different problem. In the Registry  organizationName is a key for search. It means that once someone register organization with the name google, no one will be able to do again.

So verified budges is not the solution for this issue (but of course they are required).

**Comment by raamb** [comment]
@astroseger I was referring to the twitter handle which is unique and which I am comparing to the org name in our case, but I see your point about having a separate non-unique display name.

**Comment by ksridharbabuus** [comment]
Instead of a unique sequence number we use something called GUID which is
generated by the code (no user input) before creating the organization or
service name. I remember mentioning the same in one of the discussion
thread.
This is the standard design practice that we are following for many years.
Instead of org or service name we will use the guide and display name will
be from the metadata field.

If everyone agrees we can easily implement the same.

**Comment by ksridharbabuus** [comment]
Yes we discussed to use the display name from metadata for services but not
the one from the contract which is only for the index. Even for the index
my suggestion will be dynamically generated GUID value. Which will be
unique for the index.

**Comment by astroseger** [comment]
@ksridharbabuus yes, something like GUID is a common practice (GUID is what I called globalOrgIndex for Organizations and globalServiceIndex for Services ). So it seems we are fully agree on the steps which should be done (they have been listed in my first post in this issue).

**Comment by astroseger** [comment]
So the main question now: should it be solved for betta or not?

**Comment by pennachin** [comment]
> So the main question now: should it be solved for betta or not?

Definitely yes.

**Comment by vsbogd** [comment]
@ksridharbabuus, what is the advantage of using GUID instead of incremental counter?

**Comment by astroseger** [comment]
Ah ok, I've misunderstood the term. I would prefer to generate globalOrgIndex and globalServiceIndex inside contracts simply as incremented counter (not as external GUID).  It will remove some checks inside contract, but will add disadvantages that you know your Index only after createOrganization is mined.

**Comment by astroseger** [comment]
I think we should take into account the user experience which we want user to have.  And I agree with @ferrouswheel about naming convention across singularityNet ([Naming-Standards](https://github.com/singnet/wiki/blob/master/doc/Naming-Standards.md)).

It means that it would be great if user could call services by the "universal" URI   snet:<ORGANIZATION_NAME>/<SERVICE_FULL_NAME>  (service name could include a path, but it is internal decision of the service provider) 

If we simply replace organizationName by globalOrgIndex or GUID then it will be very difficult to implement such "URI calls" in snet-cli.

But I have a proposition of design which solves everything!  (it is actually a modification of the idea we've discussed in HK)  

We simply need to implement our idea of "verified badges" on-chain. We should have separate contract which will convert organizationName to globalOrgIndex. And this contract should be partly controlled by SingularityNet foundation (yes! it is exactly how DNS works ;) ).

Let's call this new contract organizationsNameServer  (or ONS to be short).

Workflow is following:

(from the service side)
1. Service provider registers organization and receives globalOrgIndex
2. Service provider submits proposition of mapping organizationName -> globalOrgIndex to the ONS
3. Member of ONS should approve this proposition to "activate" it (to include it in the main mapping)
4. Members of ONS also have the power to remove this mapping if necessary (organization owner also has such power), but members of ONS cannot rename organization.

We also could implement ONS completely off-chain, as was discussed in HK. But it might be more transparent for the community to implement it on-chain.

**Comment by ksridharbabuus** [comment]
@astroseger The way DNS works little different as any organization(Company) register for the 2nd level domain and they manage from 3rd level with their organization (Company).
Instead of going with the complex ONS approach we can go with a simple routing concept to resolve the URI (/OrgGUID/Service[/ServicePath]) and redirect to the respective services by daemon.
Right now I dont see any need to manage ONS onChain.

**Comment by astroseger** [comment]
@ksridharbabuus 
1. the disadvantage of OrgGUID is exactly because it is externally generated! How would you prevent someone to have "OrgGUID" = "google"? 
2. The function of ONS is twofold:
       - translate OrganizationName to OrganizationIndex (or OrgGUID if I will fail to convience you that externally generated GUID is bad). How are you going to translate OrganizationName to OrganizationIndex/OrganizationGUID?
       - transparent way of implement "verified badges". How are you going to inform users which Organization was verified by the foundation?

**Comment by ferrouswheel** [comment]
Thanks Sergey for thinking of this. I'm very much in favour of the `<ORGANIZATION_NAME>/<SERVICE_FULL_NAME>` way of referring to a service.

e.g. `snet/face-services` is much nicer than `1/face-services`

**Comment by ksridharbabuus** [comment]
@astroseger Please note that anyone can guess the ServiceId very easily in case if we are going with the sequence numbers. This is one of the reason we use GUID to refer any service.

**Comment by raamb** [comment]
I am not entirely certain that we need another component ONS to handle verification. My proposal is as follows

- Have an orgIndex (unique) and org name (non-unique)
- We use the combination of orgIndex and serviceName
- Consider reserving some big names such as (google, microsoft etc) which are given out post verification. Valerio proposed this on our last call
- Even if above is not done its OK. We end up with multiple google organizations but the foundation will only verify the valid organization.

**Comment by astroseger** [comment]
The purpose of ONS is not only handle verification, but also to translate organizationName to organizationIndex.

We should provide users possibility to call service using organizationName + serviceFullName (see #80 about fixing issue with serviceFullName). 

How we are going to handle it without ONS? 
With ONS is very straightforward:
1. User call ONS and translate organiationName to organizationIndex
2. User call Registry with providing organizationIndex + serviceFullName, and get service metadata

But how we will handle it without ONS?

**Comment by astroseger** [comment]
Another way would be to not have organizationName at all, or have it only for display, but in order to make any calls user should know organizationId (in this case it can be organizationGUID, because in this case we will not have problem with phishing )....

**Comment by raamb** [comment]
> The purpose of ONS is not only handle verification, but also to translate organizationName to organizationIndex.
> 
> We should provide users possibility to call service using organizationName + serviceFullName (see #80 about fixing issue with serviceFullName).
> 
> With ONS is very straightforward:
> 
> 1. User call ONS and translate organiationName to organizationIndex
> 2. User call Registry with providing organizationIndex + serviceFullName, and get service metadata
> 
> But how we will handle it without ONS?

I am considering organizationIndex as the primary key which the provider retains. They can use this for look up not organizationName as that is non unique. 
ONS introduces an additional workflow for SingularityNet which I would like to avoid if possible.

**Comment by ksridharbabuus** [comment]
@raamb I don't recommend OrganizationIndex for this functionality as there is lots of scope for phishing. Looking at leveraging the OrgGUID for this purpose where it is going to be unique and limits the phishing activities.

**Comment by raamb** [comment]
Yes, absolutely it will be a guid.

Thanks,
Raam

**Comment by astroseger** [comment]
@ksridharbabuus @raamb   I want to say that everything depends on how we are going to use Registry.

It is orgGUID who pose very serious problem of phishing in the case if we support both calls:
- organizationName + serviceName
- organizationGUID + serviceName

Am I right that organizationGUID is externally generated?
It means that someone can register orgaganization with organizationGUID = other organizationName

But of course if we do not support organizationName + serviceName then it is not a problem

**Comment by astroseger** [comment]
Maybe we could generate GUID inside registry contract? 
OrganizationGUID = GUID(kekack256(abi.encodePacked(block.number,  random_number_provided_by_sender)))

**Comment by vsbogd** [comment]
I don't understand why externally generated GUID is better than internal counter from phishing perspective.

**Comment by pennachin** [comment]
It is highly desirable to be able to find services using organization "names" as posited by @ferrouswheel. Of course if org names aren't unique this can become complex or result in a 1:N mapping; still it is highly desirable from a usability perspective. Requiring the use of a GUID for actual calls should be fine.  It's also fine to have just an organizationDisplayName that can be used for these purposes.

We really would rather not have to bother with the ONS idea, especially for the beta release. 

> Consider  reserving some big names such as (google, microsoft etc) which are given out post verification. 

Hmm, no. We're not going to presume for other organizations and we don't want to be seen as playing favorites.

**Comment by astroseger** [comment]
Without something like ONS, or some external service, we will not be able to call service using by organizationDisplayName in snet-cli, so will it be ok that in snet-cli we will support the call only via organizationId?

**Comment by ksridharbabuus** [comment]
> 
> 
> @ksridharbabuus
> Everything depend on the way how we are going to use the Registry.
> I've just explainedm that in the architecture, how I saw it, any externally (in respect of Registry contract) generated organizationId ( so also organizationGUID ), have problem of phishing.
> 
> Could you describe architecture, how you see it? (because iI don't understand why organizationId could pose a phishing problem )

@astroseger It is easy to guess the sequential numbers either by increment or  decrement the number in the URI. Which forces us to go to next level of validation for the request.

**Comment by astroseger** [comment]
If you want it to GUID --- so let's it be   OrganizationGUID = kekack256(abi.encodePacked(block.number, random_number_provided_by_sender)) 
What is your argument against it? 
But I don't see why index is bad. Index is a little bit more user friendly.

**Comment by astroseger** [comment]
Ok @ksridharbabuus I will one argument in favor of externally generated GUID ;)  --- You don't need to wait your transaction to be mined in order to get your organizationId... 
But still internally generated Id (might be GUID) is safer...

**Comment by ferrouswheel** [comment]
To me, the primary issue is one around the separation of concerns. There is no need for a registry to maintain org names. There is a cost to updating a reverse mapping from name to index, and complexity for SingularityNET validating them or making guesses about which names to preregister inside the registry contract.

If the ONS contract was just a unvalidated name to Org ID/GUID mapping to begin with, we could replace it with a new ONS contract later (one that does allow name proposals and us validating them). Having it as a separate contract would avoid us impacting the underlying services that have already been  published to the registry. This is a better upgrade path, in my opinion, than deploying a new registry after the beta.

**Comment by astroseger** [comment]
If we go with this solution.. Then it will take one week (very safe estimate, hopefully much less), to implement it in snet-cli.

**Comment by astroseger** [comment]
@vsbogd  yes,  except all "external index" could be post betta.

**Comment by vsbogd** [comment]
external index for Beta can be as simple as ```map: name -> object``` withing DApp

**Comment by ksridharbabuus** [comment]
@astroseger @vsbogd we are already working on External Index (Through API) for DApp.

**Comment by raamb** [comment]
The external service we are working on is a controlled one i.e. it will be
a subset of published services as approved by the foundation.
Also do we retain types in the registry?

**Comment by astroseger** [comment]
@raamb 
Yes, of course we should retain types in the registry. I didn't disuses them for simplicity.  The problem is that Services and Types has exactly the same registration (Metadata). 
There are two possibilities:
1. We could store them separately:
listServicesForOrganization
listTypesForOrganization
getServiceRegistration
getTypeRegistration
2. We could store services and types together and distinguish them only in metadata. So in metadata we will have a key to distinguish a service and a type.
So we will have functions  listServicesOrTypesForOrganization and getServiceOrTypeRegistration

**Comment by ksridharbabuus** [comment]
@astroseger I am in favor of Option-2 and expressed the same during the Registry refactoring discussion. I dont see any point of making it as two different structures as Normalization for CRUD operations is always better than the Denormalized structure.

Anyway metadata is going to be different based on the type which is anyway going to be OffChain in IPFS. So we can go with single structure with Type Parameter. This reduces lots of complexity & simplifies the code in the registry.

**Comment by astroseger** [comment]
@raamb  Should we also rename ServiceName to ServiceId?

**Comment by raamb** [comment]
@Sergey Rodionov <sergey@singularitynet.io> yes, lets do that as we already
have the display name in the metadata.

Thanks,
Raam

**Comment by ksridharbabuus** [comment]
@astroseger @raamb Shall we also change the RepositoryName to RepositoryId as well? I am thinking it make sense to do it now.

**Comment by raamb** [comment]
#85 addresses this issue. We now have
OrgId - Unique 
OrgName - Non unique
ServiceId - Unique within an Org
DisplayServiceName (in IPFS not on contract) - Non unique service name
